version: "3"
services:
  fc-db:
    image: jsurf/rpi-mariadb
    container_name: fc-db
    restart: always
    environment:
      MYSQL_DATABASE: fc
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Asia/Tokyo
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - fc-network
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

